server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/menudb
    username: menu_user
    password: menu_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics